## Numpy array and basics 
  learn about numpy

In [4]:
import numpy as np

### Creating array from list


In [5]:
arr_1D=np.array([1,2,3,4,5])
print("1D array :",arr_1D)

arr_2D=np.array([[1,2,3],[4,5,6],[3,4,9]])
print("2D Array :",arr_2D)

1D array : [1 2 3 4 5]
2D Array : [[1 2 3]
 [4 5 6]
 [3 4 9]]


### List vs numpy Array

In [ ]:
py_List=[1,2,3]
print("Multiplication of list :",py_List*2)

array=np.array([1,4,2])  #element wise multiplication
print("Multiplication of numpy array :",array*2)

import time
start=time.time()
py_List=[i*2 for i in range(100000)]
print("\n List operation time :",time.time()-start)

start=time.time()
array=np.arange(100000)*2
print("\n numpy operation time :",time.time()-start)

Multiplication of list : [1, 2, 3, 1, 2, 3]
Multiplication of numpy array : [2 8 4]

 List operation time : 0.005586385726928711

 List operation time : 0.0012273788452148438


### Creating array from scratch

In [15]:
zeros=np.zeros((3,4))     # creating zero element array of 3 rows and 4 columns
print("Zero Array :\n",zeros)

ones=np.ones((2,5))       # creating element one array of 2 rows and 5 columns
print("Ones Array :\n",ones)  

full=np.full((2,2), 8)        # creating constant value array by using full method np.full((rows,columns), const value)
print("Array of constant value 8:\n",full)

random=np.random.random((3,4))  # random values are in between 0 and 1
print("Random Array :\n",random)  

sequence = np.arange(0,11,2)  # creating seuence array by using arange(start,stop,steps) where stop are excluded
print("Sequence Array :\n",sequence)  


Zero Array :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array :
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Array of constant value 8:
 [[8 8]
 [8 8]]
Random Array :
 [[0.92428201 0.72520479 0.40309719 0.90319699]
 [0.88984378 0.63304887 0.21933737 0.75659286]
 [0.48481817 0.28157364 0.99812581 0.70110925]]
Sequence Array :
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor

In [ ]:
vector=np.array([1,2,3])
print("Vector :",vector)
# vector is 1D array

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix :",matrix)
# matrix is 2D array

tensor=np.array([[[1,2,3],[4,5,6]],
                 [ [1,2,3],[9,3,4]],
                 [[0,6,7],[3,4,1]]])
print("Tensor :",tensor)
# tensor is n dimensional array

Vector : [1 2 3]
Matrix : [[1 2 3]
 [4 5 6]]
Tensor : [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [9 3 4]]

 [[0 6 7]
  [3 4 1]]]


### Array Properties


In [ ]:
array=np.array([[1,2,3],[3,8,9]])
print("Shape :",array.shape)       # gives the detail of no. rows and columns
print("Dimension :",array.ndim)    # gives the dimension of the array 
print("Size :",array.size)         # gives the no. of total elements
print("type :",array.dtype)        # gives the datatype

Shape : (2, 3)
Dimension : 2
Size : 6
type : int64


### Array Reshaping

In [20]:
arr=np.arange(15)
print("Original Array :",arr)

Reshaped=arr.reshape((3,5))
print("Reshaped Array :",Reshaped)

flattened=Reshaped.flatten()
print("Flattened Array :",flattened)

# ravels (return view ,instead of copy)
ravel=Reshaped.ravel()
print("Raveled Array :",ravel)

# Transpose
transpose=Reshaped.T
print("Transpose Array :",transpose)


Original Array : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Reshaped Array : [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Flattened Array : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Raveled Array : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Transpose Array : [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
