## Numpy Array Operation

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing",arr[2:8])
print("With Step",arr[2:8:2])
print("Negative Indexing",arr[-6])

Basic Slicing [3 4 5 6 7 8]
With Step [3 5 7]
Negative Indexing 5


In [4]:
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("specific element :",arr_2D[2][1])
print("Entire row :",arr_2D[2])
print("Entire column :",arr_2D[:,1])

specific element : 8
Entire row : [7 8 9]
Entire column : [2 5 8]


## Sorting

In [8]:
unsorted=np.array([3,2,5,1,6,9,7,8])
print("Sorted Array :",np.sort(unsorted))

arr_2D_unsorted=np.array([[2,1],[7,6],[3,5]])
print("Sorted 2D array by column :",np.sort(arr_2D_unsorted,axis=0))
print("Sorted 2D array by row :",np.sort(arr_2D_unsorted,axis=1))

Sorted Array : [1 2 3 5 6 7 8 9]
Sorted 2D array by column : [[2 1]
 [3 5]
 [7 6]]
Sorted 2D array by row : [[1 2]
 [6 7]
 [3 5]]


## Filtering


In [10]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
Even_num=arr[arr%2==0]
print(Even_num)

[ 2  4  6  8 10]


## Filter with mask

In [11]:
mask = arr>4
print("numbers greater than 4 in array",arr[mask])

numbers greater than 4 in array [ 5  6  7  8  9 10]


## Fancy Indexing vs np.where()

In [13]:
indeces =[2,6,9]
print(arr[indeces])

where_num=np.where(arr>6)
print("np array where :",arr[where_num])

[ 3  7 10]
np array where : [ 7  8  9 10]


In [ ]:
condition_arr=np.where(arr>4,True,False)
print(condition_arr)

# where it is like 
# if(arr>4):
#     True
# else:
#     False

[False False False False  True  True  True  True  True  True]


### Adding and removing data

In [15]:
arr1=np.array([1,4,6])
arr2=np.array([3,7,1])

# for merging both array you can't simply add(arr1 + arr2) them like before cause it returns after sum the same indeces element 

arr3=np.concatenate((arr1,arr2))
print("After merging :",arr3)

After merging : [1 4 6 3 7 1]


## Array Compatibility

In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6,11])
c = np.array([7,8,9])

print("Array Compatible :", a.shape == b.shape)

Array Compatible : False


In [ ]:
orig =np.array([[1,2],[3,6]])
new_row = np.array([7,8])

with_new_row=np.vstack((orig,new_row))
print("Original :",orig)
print("After adding new row :",with_new_row)

# new_col=np.array([2,7])  It gives error due to dimension mismatch
new_col=np.array([[2],[7]])
with_new_col=np.hstack((orig,new_col))
print("Original :",orig)
print("After adding new col :",with_new_col)

Original : [[1 2]
 [3 6]]
After adding new row : [[1 2]
 [3 6]
 [7 8]]
Original : [[1 2]
 [3 6]]
After adding new col : [[1 2 2]
 [3 6 7]]


In [21]:
arr=np.array([3,5,7,8,1,4])
After_Deleted= np.delete(arr,5)         # np.delete(arrayname, index)
print("Array after deletion :", After_Deleted)

Array after deletion : [3 5 7 8 1]
